/* Transcription of src/engines/wavetable.ts.
 *
 * A WavetableOsc scans across the frames of a mipmapped table. The scan
 * position is the position param plus a bipolar LFO (scan_rate,
 * scan_depth) plus the amp envelope scaled by env_to_position, clamped to
 * 0..1. One Adsr drives both the amp and the position modulation. An
 * optional Svf lowpass sits after the oscillator.
 *
 * WHAT THIS COSTS, because it is the only engine here whose answer is not
 * obviously yes. The voice itself is 224 bytes of RAM, measured below, but
 * it reads a band limited mipmap that the TypeScript builds at boot with an
 * FFT per frame per level. There is no heap and no boot budget for that, so
 * the table lives in flash: dsp/wavetable_tables.h, generated by
 * tools/gen-tables.mjs.
 *
 * At the length the TypeScript uses, 2048 points, that table is 327680
 * bytes. A part with 256 KB of flash cannot hold it at any price, and the
 * default here is therefore 512 points and 65536 bytes. That is a real
 * reduction and not a free one, measured at 44100 Hz, worst case over
 * fundamentals from 30 Hz to 4 kHz, as the loudest non-harmonic bin
 * relative to the fundamental:
 *
 *   2048 points  327680 bytes  -73 dB
 *   1024 points  147456 bytes  -58 dB
 *    512 points   65536 bytes  -52 dB   (the default)
 *    256 points   28672 bytes  -46 dB
 *
 * The floor comes from linear interpolation between table points, not from
 * the band limiting, and the worst case is always a low note: the
 * oscillator gives the lowest notes the level that keeps the most
 * harmonics, and that level is stored at only two points per period of its
 * top harmonic. At 2048 that level is selected below 21.5 Hz, under the
 * audio band. At 512 it is selected below 86 Hz, so the bottom two octaves
 * carry the -52 dB figure and everything above them is -62 dB or better.
 * On a board with flash to spare, regenerate at 2048 and get exactly what
 * the browser plays:
 *
 *   node tools/gen-tables.mjs --only=wavetable --wt-length=2048
 *
 * What one voice actually costs, measured on Cortex-M7 by building
 * test/sketches/s9o_wavetable.cpp with tools/size-report.sh's flags: 75400
 * bytes of flash and 1252 of RAM, against 60 and 1028 for the empty
 * baseline sketch. So the voice is 224 bytes of RAM and 75340 of flash, of
 * which 65536 is the table and about 9.8 KB is code plus the libm calls it
 * pulls in. The same sketch at 2048 points is 337552 bytes of flash, which
 * is the same code and 262144 more table.
 *
 * Two smaller departures from the JS. The engine takes no Rng: the JS
 * forks 'wt/lfo' for the scan LFO, and only the sample and hold shape
 * draws, so a sine LFO consumes that stream never. Lfo::Init with no Rng
 * owns a stream seeded 'lfo/sh', which is the same nothing. And the JS
 * voice re-derives its coefficients on every setParam; SetParams does the
 * same, unconditionally, because none of them depend on note state.
 */
#pragma once
#include "bellows/config.h"
#include "bellows/core/fastmath.h"
#include "bellows/dsp/envelopes.h"
#include "bellows/dsp/filters.h"
#include "bellows/dsp/lfo.h"
#include "bellows/dsp/wavetable.h"

namespace bellows {

class Wavetable {
 public:
  struct Params {
    float position = 0.0f;
    float scan_rate = 0.5f;
    float scan_depth = 0.0f;
    float env_to_position = 0.0f;
    float attack = 0.005f;
    float decay = 0.1f;
    float sustain = 0.8f;
    float release = 0.2f;
    /* A switch rather than a mix, as in the JS: the lowpass is in circuit
     * at 0.5 and up and bypassed below it. */
    float filter = 0.0f;
    float cutoff = 8000.0f;
    float resonance = 0.1f;
    float pan = 0.0f;
  };

  void Init(float sample_rate) {
    Params d;
    Init(sample_rate, kWtMorph, d);
  }

  void Init(float sample_rate, const Params& p) { Init(sample_rate, kWtMorph, p); }

  /* Any table the generator emits, so a project can ship its own frames
   * instead of the morph set. This is what makeWavetableEngine() is for in
   * the JS, minus the engine registry it wraps the set in. */
  void Init(float sample_rate, const WavetableMip& table, const Params& p) {
    p_ = p;
    osc_.Init(sample_rate, table);
    lfo_.Init(sample_rate);
    lfo_.SetShape(LfoShape::kSine);
    svf_.Init(sample_rate);
    svf_.SetMode(SvfMode::kLp);
    env_.Init(sample_rate);
    Apply();
  }

  void SetParams(const Params& p) {
    p_ = p;
    Apply();
  }

  void NoteOn(float freq, float vel) {
    vel_ = vel;
    osc_.SetFreq(freq);
    osc_.Reset(0.0f);
    lfo_.Reset(0.0f);
    svf_.Reset();
    env_.Reset();
    env_.Trigger();
  }

  void NoteOff() { env_.Release(); }

  void Process(float* l, float* r, int from, int to) {
    if (!env_.Active()) return;
    const bool use_filter = p_.filter >= 0.5f;
    const float base = p_.position;
    const float depth = p_.scan_depth;
    const float env_amt = p_.env_to_position;
    const float vel = vel_;
    for (int i = from; i < to; ++i) {
      const float e = env_.Process();
      osc_.SetPosition(base + depth * lfo_.Process() + env_amt * e);
      float y = osc_.Process();
      if (use_filter) y = svf_.Process(y);
      y *= e * vel;
      l[i] += y * gain_l_;
      r[i] += y * gain_r_;
    }
  }

  bool Active() const { return env_.Active(); }

 private:
  void Apply() {
    env_.Set(p_.attack, p_.decay, p_.sustain, p_.release);
    lfo_.SetFreq(p_.scan_rate);
    /* resonance 0..1 maps to Q 0.5..10, which is the JS mapping. */
    svf_.Set(p_.cutoff, 0.5f + p_.resonance * 9.5f);
    const float angle = ((Clamp(p_.pan, -1.0f, 1.0f) + 1.0f) * kPi) / 4.0f;
    gain_l_ = fm::Cos(angle);
    gain_r_ = fm::Sin(angle);
  }

  Params p_;
  WavetableOsc osc_;
  Lfo lfo_;
  Svf svf_;
  Adsr env_;

  float vel_ = 1.0f;
  float gain_l_ = kSqrtHalf, gain_r_ = kSqrtHalf;
};

}  // namespace bellows
