/*
 * Bundles the worklet entry into a single self-contained IIFE string and
 * writes it to src/kernel/worklet-code.gen.ts. The main bundle imports that
 * constant and loads it through a blob URL, so consumers never deal with a
 * second file. Run before build and after kernel or engine changes:
 *
 *   node scripts/gen-worklet.mjs
 */

import { build } from 'esbuild';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = join(here, '..');

const result = await build({
  entryPoints: [join(pkg, 'src/kernel/worklet-entry.ts')],
  bundle: true,
  format: 'iife',
  target: 'es2022',
  minify: true,
  write: false,
  legalComments: 'none',
});

const code = result.outputFiles[0].text;
const out =
  '/* Generated by scripts/gen-worklet.mjs. Do not edit by hand. */\n' +
  '// prettier-ignore\n' +
  'export const workletCode: string = ' +
  JSON.stringify(code) +
  ';\n';

writeFileSync(join(pkg, 'src/kernel/worklet-code.gen.ts'), out);
console.log('worklet bundle: ' + (code.length / 1024).toFixed(1) + ' KB');
