<script setup lang="ts">
/*
 * The LLM references, both of them, behind a BROWSER and EMBEDDED switch.
 *
 * There are two generated documents and this page used to offer one. The
 * browser reference comes from scripts/gen-llm-ref.mjs, which interrogates the
 * BUILT library; the embedded one comes from scripts/gen-llm-embedded.mjs,
 * which parses the C++ headers because there is no built artefact to ask. Both
 * ship in public/ and both were reachable by URL, but only /llm.txt was
 * reachable by clicking, so the embedded reference existed and could not be
 * found. The CODE page and the docs tree already switch this way; this page
 * was the one that did not.
 */

import { computed, ref, watch } from 'vue';

interface Reference {
  id: 'browser' | 'embedded';
  label: string;
  file: string;
  blurb: string;
}

const REFS: Reference[] = [
  {
    id: 'browser',
    label: 'BROWSER',
    file: '/llm.txt',
    blurb:
      'Paste this into any AI assistant and it will know the entire bellowsjs API: every engine and effect with exact parameter ranges, the facade, theory, sequencing, analysis, and the rules that keep integrations correct. Generated from the library source and its type declarations, so it matches the published npm package exactly.',
  },
  {
    id: 'embedded',
    label: 'EMBEDDED',
    file: '/llm-embedded.txt',
    blurb:
      'The same thing for the C++ port: every header, class and Params struct with the defaults the header sets, plus how to install it under PlatformIO and the Arduino IDE, the build flags, and which boards were measured to build. Generated by parsing the headers, because a header-only library has no built artefact to interrogate.',
  },
];

const current = ref<Reference['id']>('browser');
const ref_ = computed(() => REFS.find((r) => r.id === current.value)!);

const text = ref('');
const failed = ref(false);
const copied = ref(false);

async function load(file: string): Promise<void> {
  text.value = '';
  failed.value = false;
  try {
    const res = await fetch(file);
    if (!res.ok) throw new Error(String(res.status));
    text.value = await res.text();
  } catch {
    failed.value = true;
  }
}

watch(ref_, (r) => void load(r.file), { immediate: true });

async function copyAll() {
  try {
    await navigator.clipboard.writeText(text.value);
    copied.value = true;
    setTimeout(() => (copied.value = false), 1800);
  } catch {
    // selection fallback: the text is selectable below
  }
}

function sizeLabel(): string {
  if (!text.value) return '';
  return (text.value.length / 1024).toFixed(1) + ' KB // ' + text.value.split('\n').length + ' lines';
}
</script>

<template>
  <div class="refpage">
    <section class="panel">
      <div class="panel-title">
        llm reference <em>{{ sizeLabel() }}</em>
        <span class="actions">
          <a class="raw" :href="ref_.file" target="_blank" rel="noopener">RAW {{ ref_.file }}</a>
          <button class="lit" :disabled="!text" @click="copyAll">{{ copied ? 'COPIED' : 'COPY ALL' }}</button>
        </span>
      </div>

      <div class="row switch">
        <button
          v-for="r in REFS"
          :key="r.id"
          :class="{ lit: r.id === current }"
          @click="current = r.id"
        >
          {{ r.label }}
        </button>
      </div>

      <p class="lead">{{ ref_.blurb }}</p>
      <pre v-if="text"><code>{{ text }}</code></pre>
      <p v-else-if="failed" class="lead">
        Could not load {{ ref_.file }}. The raw file link above may still work.
      </p>
      <p v-else class="lead">loading...</p>
    </section>
  </div>
</template>

<style scoped>
.actions {
  display: flex;
  gap: 8px;
  align-items: center;
}

.actions button {
  box-shadow: none;
  padding: 4px 12px;
  font-size: 10px;
}

.switch {
  display: flex;
  gap: 8px;
  margin-bottom: 12px;
}

.raw {
  font-size: 10px;
  letter-spacing: 0.14em;
  color: var(--tick);
  text-decoration: none;
  border: 1px solid var(--seam);
  padding: 4px 10px;
}

.raw:hover {
  color: var(--phosphor);
  border-color: var(--phosphor);
}

.lead {
  font-size: 12px;
  color: var(--tick);
  line-height: 1.6;
  margin-bottom: 12px;
  max-width: 760px;
}

pre {
  background: var(--iron);
  border: 1px solid var(--seam);
  padding: 16px;
  overflow: auto;
  max-height: 70vh;
  font-size: 11.5px;
  line-height: 1.6;
  color: var(--bone);
  user-select: all;
}
</style>
