/*
 * Realtime kernel loader. The worklet code ships inside the bundle as a
 * string constant (generated by scripts/gen-worklet.mjs) and loads through
 * a blob URL, so there is no second file to deploy. Hosts with a strict
 * script-src CSP that blocks blob: can pass their own URL to the copy of
 * dist/worklet.js published in the package.
 */

import { workletCode } from './worklet-code.gen';
import type { KernelMessage, KernelReply } from './messages';

export const KERNEL_PROCESSOR_NAME = 'bellows-kernel';

let blobUrl: string | null = null;

function kernelUrl(): string {
  if (!blobUrl) {
    blobUrl = URL.createObjectURL(new Blob([workletCode], { type: 'application/javascript' }));
  }
  return blobUrl;
}

export interface KernelNode {
  node: AudioWorkletNode;
  post(msg: KernelMessage, transfer?: Transferable[]): void;
  onReply(cb: (reply: KernelReply) => void): void;
  dispose(): void;
}

export async function createKernelNode(
  ctx: BaseAudioContext,
  opts?: { workletUrl?: string },
): Promise<KernelNode> {
  const url = opts?.workletUrl ?? kernelUrl();
  try {
    await ctx.audioWorklet.addModule(url);
  } catch (err) {
    throw new Error(
      'bellows: failed to load the kernel worklet. If your Content-Security-Policy blocks blob: ' +
        'script sources, pass { workletUrl } pointing at the packaged dist/worklet.js. Cause: ' +
        String(err),
    );
  }
  const node = new AudioWorkletNode(ctx, KERNEL_PROCESSOR_NAME, {
    numberOfInputs: 1,
    numberOfOutputs: 1,
    outputChannelCount: [2],
  });
  const listeners = new Set<(reply: KernelReply) => void>();
  node.port.onmessage = (e: MessageEvent) => {
    for (const cb of listeners) cb(e.data as KernelReply);
  };
  return {
    node,
    post(msg, transfer) {
      if (transfer && transfer.length) node.port.postMessage(msg, transfer);
      else node.port.postMessage(msg);
    },
    onReply(cb) {
      listeners.add(cb);
    },
    dispose() {
      node.port.onmessage = null;
      node.disconnect();
    },
  };
}
