/* Generated by scripts/gen-worklet.mjs. Do not edit by hand. */
/* Placeholder until the first generation run; the build regenerates this. */
// prettier-ignore
export const workletCode: string = '';
